services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: medicare-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
